apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: altinn3-proxy
  tags: []
  title: Altinn3 integrasjon
spec:
  type: service
  lifecycle: experimental
  owner: digibok

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: altinn3-motor
spec:
  type: service
  owner: digibok
  lifecycle: experimental
  dependsOn:
    - resource:default/grunnboksdatabasen
    - resource:default/altinn3-persistence

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: altinn3-persistence
  title: Altinn3 transit database
spec:
  type: database
  owner: digibok

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: altinn3-api
spec:
  type: openapi
  owner: digibok
  lifecycle: production
  definition:
    $text: https://github.com/kartverket/altinn3-proxy/blob/main/specs/altinn-broker-v1.json

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: altinn3-events-server
spec:
  type: service
  owner: digibok
  lifecycle: experimental
  consumesApis:
    - altinn3-api
  dependsOn:
    - resource:default/altinn3-persistence

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testkomponent-slett
spec:
  type: service
  owner: digibok
  lifecycle: production
  system: grunnbok
