style:
  WildcardImport:
    active: false
  BracesOnIfStatements:
    active: false
  ForbiddenComment:
    active: false

formatting:
  ImportOrdering:
    active: false
  NoWildcardImports:
    active: false
  MultiLineIfElse:
    active: false
